version: '3.7'
services:
    postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        ports:
        - 5432:5432
        volumes:
        - ./volumes/postgres/:/var/lib/postgresql/data/

    pgbouncer:
        image: pgbouncer/pgbouncer:1.13.0
        environment:
            DATABASES_CLIENT_SIDE_DBNAME: foobar
            DATABASES_HOST: postgres
            DATABASES_PORT: 5432
            DATABASES_DBNAME: postgres
            PGBOUNCER_LISTEN_PORT: 5532
            PGBOUNCER_AUTH_TYPE: md5
            PGBOUNCER_AUTH_FILE: /config/userlist.txt
        ports:
        - 5532:5532
        volumes:
        - ./config/:/config/